setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
ankieta = read.csv('ankieta.csv', na.strings=c(""," ","NA","nie wie","nie wiem","nieczytelne pismo", "dualizm odpowiedzi","brak odpowiedzi","nie pami??ta"))
obserwacje = read.csv('obserwacje.csv', na.strings = c("", " ", "NA"))



###Cleaning - ankieta

for (i in 1:dim(obserwacje)[2]){
  obserwacje[,i] = trimws(obserwacje[,i])
}

#Order levels
ankieta$klasyfikacja_z = ordered(ankieta$klasyfikacja_z,
                                 levels = c("ca??kowicie niezwi??zany z science",
                                            "po??rednio zwi??zany z science",
                                            "bezpo??rdnio zwi??zany z science"))
time_frequency = c(21, 38:49)
for (i in time_frequency)
{
  ankieta[, i] = ordered(ankieta[, i],
                         levels = c("nigdy albo rzadko (raz w roku)", "kilka razy w roku",
                                    "raz lub dwa razy w miesi??cu", "raz w tygodniu",
                                    "prawie codziennie"))
}

agreement_levels = c(50:60)
time_frequency = c(21, 38:49)
for (i in time_frequency)
{
  ankieta[, i] = ordered(ankieta[, i],
                         levels = c("zdecydowanie si?? nie zgadzam", "raczej si?? nie zgadzam",
                                    "ani si?? zgadzam ani si?? nie zgadzam", 
                                    "raczej si?? zgadzam", "zdecydowanie si?? zgadzam"))
}

ankieta$p_16_2_4 = ordered(ankieta$p_16_2_4,
                           levels = c("nie ma ani jednej", "kilka (mniej ni?? 20)",
                                      "du??o (od 20 do 50)", "bardzo du??o (wi??cej ni?? 50 do 100)",
                                      "ca??e mn??stwo (wi??cej ni?? 100)"))


###Cleaning - obserwacje
for (i in 1:dim(ankieta)[2]){
  ankieta[,i] = trimws(ankieta[,i])
}

obserwacje[is.na(obserwacje$galeria),"galeria"] = "<brak>"

levels(obserwacje$eksponat) = c(levels(obserwacje$eksponat), "PRZERWA")
obserwacje[obserwacje$kategorie==1,]$eksponat = "PRZERWA"
obserwacje[obserwacje$eksponat=="INNE - PLANETARIUM",]$eksponat <- "PLANETARIUM"

oldw <- getOption("warn")
options(warn = -1)
for (i in 13:21){
  obserwacje[,i] = as.numeric(as.character(obserwacje[,i]))
  obserwacje[,i][obserwacje[,i]<100] = NA
}
options(warn=oldw)


ankieta$zaw??d_matki<-sub("adwokat", "Humanistyczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("adwokat lub aktorka", "Humanistyczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("agent ubezpieczeniowy", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("akrobata", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("aktorka", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("aktorka albo opiekunka dzieci2", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("aktorka lub opiekunka dzieci", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("aktorka lub redaktorka gazety", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("akwokat, piosenkarz, w??a??ciciel firmy", NA, ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("architekt", "Techniczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("architekt wn??trz", "Techniczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("architekt, astronom, modelka, aktorka", NA, ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("architekt, in??ynier", "Techniczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("architekt, youtuber", "Techniczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("astronauta", "Techniczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("astronom", "Techniczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("auczyciel angielskiego lub fryzjer", NA, ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("bankier", "Techniczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("bibliotekarka", "Humanistyczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("biegaczka", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("brukarz", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("budowlanie, tynkarz", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("budowlaniec", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("celnik", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("chemik", "Przyrodniczy", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("chirurg", "Przyrodniczy", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("cukiernik", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("dentysta albo weterynarz", "Przyrodniczy", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("dietetyk", "Przyrodniczy", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("doradca rolniczy", "Przyrodniczy", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("dostawca", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("drukarz", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("ekonomista", "Techniczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("elektryk", "Techniczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("energetyk", "Techniczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("farmaceutka", "Przyrodniczy", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("farmaceutka lub przedszkolanka", NA, ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("foograf albo fryzjer", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("forogaf albo informatyk", NA, ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("fotograf", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("fotograf albo architekt", NA, ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("fotograf lub prawnik, ewentulanie co????? zwi??zanego", NA, ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("fryzjer", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("fryzjer lub dentysta", NA, ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("fryzjerka", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("fryzjerka albo przedszkolanka", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("fryzjerka, kosmetyczka", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("g????rnik", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("g??????wny specjalista ds..", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("g????wna ksi??gowa", "Techniczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("gospodyni domowa", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("hadlowiec", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("handlowiec", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("hodowca zwierz??t", "Przyrodniczy", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("hydraulik", "Techniczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("informatyk", "Techniczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("informatyk i gracz komputerowy", "Techniczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("informatyk programista", "Techniczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("informatyk, fryzjer, kosmetyczka", NA, ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("informatyk, in??ynier", "Techniczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("informatyk, programista, grafik komputerowy", "Techniczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("informatyk, proplayer", "Techniczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("informatyk, tw????rca gier", "Techniczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("informatyk, zapa?????nik", NA, ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("in??ynier", "Techniczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("in??ynier budowlany", "Techniczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("je??dziec konny", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("jokerka albo nauczycielka plastyki", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("jubiler", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("kadrowa w ZUS", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("kelnerka", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("kierowca", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("kierowca ci??????ar????wki", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("kierowca TIR-????w", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("kierownik ds. kontroli ja", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("kierownik hurtowni", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("kierownik sklepu", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("kierownik wydzia??u", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("konserwator lewego brzgu", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("konsultantka Avon", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("kosmetyczka", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("kosmetyczka, makija????ystka", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("krawcowa", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("krawcowa, dekororka sal", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("krawiec", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("ksi??dz", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("ksi??goowa", "Techniczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("kucharka", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("kucharz", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("kurator s??dowy", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("kwiaciarka", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("?????lusarz", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("?????piewak", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("labserwis", "Techniczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("lakiernik", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("lekarz", "Przyrodniczy", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("lekarz i prawnik", NA, ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("lekarz lub hipoterapeuta", "Przyrodniczy", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("lekarz lub ksi??gowa", NA, ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("lekarz pediaatra", "Przyrodniczy", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("lekarz pediatra", "Przyrodniczy", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("lekarz, naukowiec, in??ynier", NA, ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("le??nik", "Przyrodniczy", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("????o??nierz", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("logopeda i nauczyciel", "Humanistyczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("????czy kable", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("magazynier", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("malarka i nauczycielka plastyki", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("maluje maszyny", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("masa????ysta za granic??", "Przyrodniczy", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("masarz", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("mechaink samochodowy", "Techniczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("mechanik", "Techniczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("mechanik i lakiernik", "Techniczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("mechanik rowerowy, fryzjer, podr????????nik", NA, ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("mechanik samochodowy", "Techniczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("mechanik sportowy", "Techniczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("medycyna, policjatnka lub rolnik", NA, ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("menad????er klubu pi??karskiego", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("menad????er w banku", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("monta????ysta film????w", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("monter drzwi i okien", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("monter kamer i serwisant", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("murarz", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("nauczyciel", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("nauczyciel historii", "Humanistyczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("nauczyciel matematyki", "Techniczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("nauczyciel wf-u", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("nauczyciel, lekarz", NA, ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("nauczycielka", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("nauczycielka biologii", "Przyrodniczy", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("nauczycielka geografii", "Przyrodniczy", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("nauczycielka j??z. Angiel", "Humanistyczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("nauczycielka polskiego", "Humanistyczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("nauczycielka przedsi??bio", "Humanistyczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("nauczycielka wf-u", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("nauczycielka wf-u lub lekarka", NA, ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("nauczycielka wf-u lub malarka", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("nauczycielka, piosenkarka, makijarzyystka", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("naukowiec", "Techniczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("obs??uguje klient????w", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("ogrodniczka", "Przyrodniczy", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("ogrodnik", "Przyrodniczy", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("operator koparki", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("operator maszyn", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("operator w????zka wid??oweg", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("opiekunka", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("opiekunka dla dzieci, farmaceutka, nauczycielka lu", NA, ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("opiekunka dzieci", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("opiekunka w autobusie szk", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("organizator wycieczek", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("otworzy????? sswoj?? cukierni?? lub pracowa????? w domu", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("pakuje cz???????ci samochodo", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("pakuje kosmetyki", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("pedagog", "Humanistyczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("pedagog lub fotograf", NA, ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("pediatra lub neurolog", "Przyrodniczy", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("piekarz", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("piel??gniarka", "Przyrodniczy", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("pilot", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("pi??karz", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("pi??karz albo prezydent, premier", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("pi??karz lub informatyk", NA, ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("pi??karz lub murarz", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("pi??karz, ksi??dz, menad????er", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("piosenkara", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("pisarz komiks????w i filozof", "Humanistyczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("plantator", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("po?????rednik nieruchomo?????ci", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("policjant", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("policjant lub informatyk", NA, ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("policjant lub kryminolog", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("policjant lub stolarz", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("policjant lub Youtuber", NA, ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("policjantka", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("policjantka lub fryzjerka", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("po??o??na", "Przyrodniczy", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("praca przy komputerze", "Techniczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("pracownik biurowy", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("pracownik kopalni", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("pracownik linii produkcyj", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("pracownik spo??eczny", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("pracownik ZUK", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("pracuje na stacji benzyno", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("pracuje w domu", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("pracuje w dworku", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("pracuje w fabryce ciastek", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("pracuje w firmie", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("pracuje w Interdruku", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("pracuje w kopalni", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("pracuje w kopalni piasku", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("pracuje w sedarze", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("pracuje w skupie z??omu", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("pracuje w szkole", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("prawnik", "Humanistyczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("prawnik lub lekarz", NA, ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("prawnik, lekarz, pi??karz", NA, ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("prezenterka telewizyjna lub s??dzia", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("produkuje sery", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("projektantka wn??trz", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("projektowanie motor????w albo stolarz", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("prowadzi firm?? budowlan??", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("prowadzi swoj?? firm?? br", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("prowadzi w??asn?? dzia??a", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("prowadzi????? stadnin?? koni", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("przedstawiciel handlowy", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("przedszkolanka", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("psycholog dzieci??cy", "Humanistyczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("ratownik, nauczyciel, weterynarz", NA, ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("recepcjonistka w hotelu", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("re????yserka lub aktorka", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("restaurator, szef kuchni", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("rolnik", "Przyrodniczy", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("rolnik (naprawa maszyn)", NA, ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("rolnik i kierowca TIR-????w", NA, ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("rolnik lub kierowca TIR-????w", NA, ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("sekretarka", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("s??dzia", "Humanistyczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("siatkarka", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("skrzypaczka", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("spawacz", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("specjalista ds. kadr i p??", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("sportowiec", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("sprawdza czy jest wszystk", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("sprawdza jako?????????? roli", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("sprz??taczka", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("sprzedawca", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("sprzedawca cz???????ci samoc", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("sprzedawca mebli", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("sprzedawca, rolnik", NA, ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("stewardesa", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("stolarz", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("stra????ak", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("szef ekipy budowlanej", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("szewc", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("szwaczka", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("taks????wkarz", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("tancerka", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("tancerka, nauczycielka wf, sprzedawca", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("tatua????ystka", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("technolog mebli", "Techniczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("tester gier komputerowych", "Techniczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("tokarz", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("tynkarz", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("urz??dnik", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("urz??dnik, sekretarz", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("w AVON", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("w banku", NA, ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("w biurze poselskim", NA, ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("w drukarni", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("w eletrociep??owni", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("w firmie obuwniczej", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("w firmie produkcyjnej", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("w firmie produkuj??cej ok", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("w firmie przewozowej", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("w gospodarstwie", "Przyrodniczy", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("w hotelu", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("w internecie", "Techniczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("w kanalizacji", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("w MOP sortuje ?????mieci", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("w o?????rodku dla os????b niep", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("w o?????rodku opieku?????czym", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("w rolnictwie", "Przyrodniczy", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("w sklepie internetowym", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("w stra????y po????arnej", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("w szpitalu", "Przyrodniczy", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("w tartaku", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("w transporcie", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("w zak??adzie mi??snym", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("w zak??adzie produkcyjnym", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("w????jt gminy", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("wdra????a systemy integracy", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("weterynarz", "Przyrodniczy", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("weterynarz lub projektantka mody", NA, ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("weterynarz, pisarka albo podr????????niczka", NA, ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("w??dzi mi??so", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("wice dyrektor firmy", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("w??a??ciciel firmy motory", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("w??a??ciciel piekarni", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("w??a??ciciel restauracji", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("w??a??ciciel restauracji lub zak??adu fryzjerskieg", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("wojskowy", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("wstawia parapety", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("wyko?????czenia mieszka?????", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("wykonuje okna dachowe", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("wypisuje zam????wienia", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("youtuber (gamer)", "Techniczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("Youtuber, tester gier, DJ", NA, ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("zajmowa????? si?? motoryzacj??", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("zast??pca kierownika", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("zast??pca w????jta", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("zbiera ?????mieci", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("zrywa pieczarki", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("Techniczny wn??trz", "Techniczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("Inne, Przyrodniczy", NA, ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("Inne, dekororka sal", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("Inne wf-u", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("Inne w autobusie szk", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("Inne polskiego", "Humanistyczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("Inne mebli", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("Inne j??z. Angiel", "Humanistyczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("Inne geografii", "Przyrodniczy", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("Inne biologii", "Przyrodniczy", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("Inneka", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("Inneka j??z. Angiel", "Humanistyczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("Inneka polskiego", "Humanistyczny", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("Inneka biologii", "Przyrodniczy", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("Inneka przedsi??bio", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("Inneka geografii", "Przyrodniczy", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("logopeda i Inne", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("Inneka wf-u", "Inne", ankieta$zaw??d_matki)
ankieta$zaw??d_matki<-sub("Inne przedsi??bio", "Inne", ankieta$zaw??d_matki)

df=c(ankieta$zaw??d_matki)#,ankieta$zaw??d_ojciec,ankieta$zaw??d_u)
df=unique(df)
View(as.array(df))

ankieta$zaw??d_ojciec<-sub("adwokat", "Humanistyczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("adwokat lub aktorka", "Humanistyczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("agent ubezpieczeniowy", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("akrobata", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("aktorka", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("aktorka albo opiekunka dzieci2", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("aktorka lub opiekunka dzieci", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("aktorka lub redaktorka gazety", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("akwokat, piosenkarz, w??a??ciciel firmy", NA, ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("architekt", "Techniczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("architekt wn??trz", "Techniczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("architekt, astronom, modelka, aktorka", NA, ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("architekt, in??ynier", "Techniczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("architekt, youtuber", "Techniczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("astronauta", "Techniczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("astronom", "Techniczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("auczyciel angielskiego lub fryzjer", NA, ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("bankier", "Techniczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("bibliotekarka", "Humanistyczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("biegaczka", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("brukarz", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("budowlanie, tynkarz", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("budowlaniec", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("celnik", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("chemik", "Przyrodniczy", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("chirurg", "Przyrodniczy", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("cukiernik", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("dentysta albo weterynarz", "Przyrodniczy", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("dietetyk", "Przyrodniczy", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("doradca rolniczy", "Przyrodniczy", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("dostawca", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("drukarz", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("ekonomista", "Techniczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("elektryk", "Techniczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("energetyk", "Techniczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("farmaceutka", "Przyrodniczy", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("farmaceutka lub przedszkolanka", NA, ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("foograf albo fryzjer", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("forogaf albo informatyk", NA, ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("fotograf", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("fotograf albo architekt", NA, ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("fotograf lub prawnik, ewentulanie co????? zwi??zanego", NA, ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("fryzjer", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("fryzjer lub dentysta", NA, ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("fryzjerka", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("fryzjerka albo przedszkolanka", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("fryzjerka, kosmetyczka", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("g????rnik", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("g??????wny specjalista ds..", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("g????wna ksi??gowa", "Techniczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("gospodyni domowa", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("hadlowiec", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("handlowiec", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("hodowca zwierz??t", "Przyrodniczy", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("hydraulik", "Techniczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("informatyk", "Techniczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("informatyk i gracz komputerowy", "Techniczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("informatyk programista", "Techniczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("informatyk, fryzjer, kosmetyczka", NA, ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("informatyk, in??ynier", "Techniczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("informatyk, programista, grafik komputerowy", "Techniczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("informatyk, proplayer", "Techniczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("informatyk, tw????rca gier", "Techniczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("informatyk, zapa?????nik", NA, ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("in??ynier", "Techniczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("in??ynier budowlany", "Techniczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("je??dziec konny", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("jokerka albo nauczycielka plastyki", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("jubiler", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("kadrowa w ZUS", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("kelnerka", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("kierowca", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("kierowca ci??????ar????wki", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("kierowca TIR-????w", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("kierownik ds. kontroli ja", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("kierownik hurtowni", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("kierownik sklepu", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("kierownik wydzia??u", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("konserwator lewego brzgu", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("konsultantka Avon", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("kosmetyczka", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("kosmetyczka, makija????ystka", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("krawcowa", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("krawcowa, dekororka sal", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("krawiec", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("ksi??dz", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("ksi??goowa", "Techniczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("kucharka", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("kucharz", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("kurator s??dowy", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("kwiaciarka", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("?????lusarz", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("?????piewak", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("labserwis", "Techniczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("lakiernik", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("lekarz", "Przyrodniczy", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("lekarz i prawnik", NA, ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("lekarz lub hipoterapeuta", "Przyrodniczy", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("lekarz lub ksi??gowa", NA, ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("lekarz pediaatra", "Przyrodniczy", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("lekarz pediatra", "Przyrodniczy", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("lekarz, naukowiec, in??ynier", NA, ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("le??nik", "Przyrodniczy", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("????o??nierz", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("logopeda i nauczyciel", "Humanistyczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("????czy kable", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("magazynier", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("malarka i nauczycielka plastyki", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("maluje maszyny", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("masa????ysta za granic??", "Przyrodniczy", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("masarz", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("mechaink samochodowy", "Techniczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("mechanik", "Techniczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("mechanik i lakiernik", "Techniczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("mechanik rowerowy, fryzjer, podr????????nik", NA, ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("mechanik samochodowy", "Techniczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("mechanik sportowy", "Techniczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("medycyna, policjatnka lub rolnik", NA, ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("menad????er klubu pi??karskiego", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("menad????er w banku", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("monta????ysta film????w", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("monter drzwi i okien", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("monter kamer i serwisant", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("murarz", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("nauczyciel", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("nauczyciel historii", "Humanistyczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("nauczyciel matematyki", "Techniczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("nauczyciel wf-u", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("nauczyciel, lekarz", NA, ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("nauczycielka", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("nauczycielka biologii", "Przyrodniczy", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("nauczycielka geografii", "Przyrodniczy", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("nauczycielka j??z. Angiel", "Humanistyczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("nauczycielka polskiego", "Humanistyczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("nauczycielka przedsi??bio", "Humanistyczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("nauczycielka wf-u", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("nauczycielka wf-u lub lekarka", NA, ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("nauczycielka wf-u lub malarka", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("nauczycielka, piosenkarka, makijarzyystka", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("naukowiec", "Techniczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("obs??uguje klient????w", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("ogrodniczka", "Przyrodniczy", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("ogrodnik", "Przyrodniczy", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("operator koparki", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("operator maszyn", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("operator w????zka wid??oweg", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("opiekunka", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("opiekunka dla dzieci, farmaceutka, nauczycielka lu", NA, ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("opiekunka dzieci", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("opiekunka w autobusie szk", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("organizator wycieczek", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("otworzy????? sswoj?? cukierni?? lub pracowa????? w domu", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("pakuje cz???????ci samochodo", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("pakuje kosmetyki", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("pedagog", "Humanistyczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("pedagog lub fotograf", NA, ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("pediatra lub neurolog", "Przyrodniczy", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("piekarz", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("piel??gniarka", "Przyrodniczy", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("pilot", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("pi??karz", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("pi??karz albo prezydent, premier", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("pi??karz lub informatyk", NA, ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("pi??karz lub murarz", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("pi??karz, ksi??dz, menad????er", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("piosenkara", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("pisarz komiks????w i filozof", "Humanistyczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("plantator", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("po?????rednik nieruchomo?????ci", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("policjant", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("policjant lub informatyk", NA, ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("policjant lub kryminolog", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("policjant lub stolarz", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("policjant lub Youtuber", NA, ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("policjantka", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("policjantka lub fryzjerka", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("po??o??na", "Przyrodniczy", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("praca przy komputerze", "Techniczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("pracownik biurowy", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("pracownik kopalni", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("pracownik linii produkcyj", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("pracownik spo??eczny", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("pracownik ZUK", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("pracuje na stacji benzyno", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("pracuje w domu", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("pracuje w dworku", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("pracuje w fabryce ciastek", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("pracuje w firmie", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("pracuje w Interdruku", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("pracuje w kopalni", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("pracuje w kopalni piasku", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("pracuje w sedarze", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("pracuje w skupie z??omu", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("pracuje w szkole", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("prawnik", "Humanistyczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("prawnik lub lekarz", NA, ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("prawnik, lekarz, pi??karz", NA, ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("prezenterka telewizyjna lub s??dzia", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("produkuje sery", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("projektantka wn??trz", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("projektowanie motor????w albo stolarz", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("prowadzi firm?? budowlan??", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("prowadzi swoj?? firm?? br", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("prowadzi w??asn?? dzia??a", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("prowadzi????? stadnin?? koni", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("przedstawiciel handlowy", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("przedszkolanka", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("psycholog dzieci??cy", "Humanistyczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("ratownik, nauczyciel, weterynarz", NA, ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("recepcjonistka w hotelu", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("re????yserka lub aktorka", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("restaurator, szef kuchni", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("rolnik", "Przyrodniczy", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("rolnik (naprawa maszyn)", NA, ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("rolnik i kierowca TIR-????w", NA, ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("rolnik lub kierowca TIR-????w", NA, ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("sekretarka", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("s??dzia", "Humanistyczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("siatkarka", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("skrzypaczka", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("spawacz", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("specjalista ds. kadr i p??", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("sportowiec", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("sprawdza czy jest wszystk", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("sprawdza jako?????????? roli", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("sprz??taczka", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("sprzedawca", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("sprzedawca cz???????ci samoc", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("sprzedawca mebli", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("sprzedawca, rolnik", NA, ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("stewardesa", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("stolarz", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("stra????ak", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("szef ekipy budowlanej", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("szewc", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("szwaczka", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("taks????wkarz", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("tancerka", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("tancerka, nauczycielka wf, sprzedawca", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("tatua????ystka", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("technolog mebli", "Techniczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("tester gier komputerowych", "Techniczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("tokarz", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("tynkarz", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("urz??dnik", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("urz??dnik, sekretarz", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("w AVON", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("w banku", NA, ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("w biurze poselskim", NA, ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("w drukarni", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("w eletrociep??owni", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("w firmie obuwniczej", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("w firmie produkcyjnej", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("w firmie produkuj??cej ok", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("w firmie przewozowej", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("w gospodarstwie", "Przyrodniczy", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("w hotelu", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("w internecie", "Techniczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("w kanalizacji", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("w MOP sortuje ?????mieci", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("w o?????rodku dla os????b niep", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("w o?????rodku opieku?????czym", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("w rolnictwie", "Przyrodniczy", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("w sklepie internetowym", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("w stra????y po????arnej", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("w szpitalu", "Przyrodniczy", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("w tartaku", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("w transporcie", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("w zak??adzie mi??snym", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("w zak??adzie produkcyjnym", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("w????jt gminy", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("wdra????a systemy integracy", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("weterynarz", "Przyrodniczy", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("weterynarz lub projektantka mody", NA, ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("weterynarz, pisarka albo podr????????niczka", NA, ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("w??dzi mi??so", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("wice dyrektor firmy", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("w??a??ciciel firmy motory", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("w??a??ciciel piekarni", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("w??a??ciciel restauracji", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("w??a??ciciel restauracji lub zak??adu fryzjerskieg", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("wojskowy", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("wstawia parapety", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("wyko?????czenia mieszka?????", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("wykonuje okna dachowe", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("wypisuje zam????wienia", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("youtuber (gamer)", "Techniczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("Youtuber, tester gier, DJ", NA, ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("zajmowa????? si?? motoryzacj??", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("zast??pca kierownika", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("zast??pca w????jta", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("zbiera ?????mieci", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("zrywa pieczarki", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("Techniczny wn??trz", "Techniczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("Inne, Przyrodniczy", NA, ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("Inne, dekororka sal", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("Inne wf-u", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("Inne w autobusie szk", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("Inne przedsi??bio", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("Inne polskiego", "Humanistyczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("Inne mebli", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("Inne j??z. Angiel", "Humanistyczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("Inne geografii", "Przyrodniczy", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("Inne biologii", "Przyrodniczy", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("Przyrodzniczy", "Przyrodniczy", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("Inne piasku", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("Techniczny samochodowy", "Techniczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("Inne cz???????ci samoc", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("Techniczny budowlany", "Techniczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("Inne TIR-????w", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("Inne ci??????ar????wki", "Inne", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("Inne historii", "Humanistyczny", ankieta$zaw??d_ojciec)
ankieta$zaw??d_ojciec<-sub("Techniczny budowlany", "Techniczny", ankieta$zaw??d_ojciec)

df=c(ankieta$zaw??d_matki,ankieta$zaw??d_ojciec)#,ankieta$zaw??d_u)
df=unique(df)
View(as.array(df))

ankieta$zaw??d_u<-sub("adwokat", "Humanistyczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("adwokat lub aktorka", "Humanistyczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("agent ubezpieczeniowy", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("akrobata", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("aktorka", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("aktorka albo opiekunka dzieci2", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("aktorka lub opiekunka dzieci", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("aktorka lub redaktorka gazety", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("akwokat, piosenkarz, w??a??ciciel firmy", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("architekt", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("architekt wn??trz", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("architekt, astronom, modelka, aktorka", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("architekt, in??ynier", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("architekt, youtuber", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("astronauta", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("astronom", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("auczyciel angielskiego lub fryzjer", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("bankier", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("bibliotekarka", "Humanistyczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("biegaczka", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("brukarz", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("budowlanie, tynkarz", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("budowlaniec", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("celnik", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("chemik", "Przyrodniczy", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("chirurg", "Przyrodniczy", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("cukiernik", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("dentysta albo weterynarz", "Przyrodniczy", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("dietetyk", "Przyrodniczy", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("doradca rolniczy", "Przyrodniczy", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("dostawca", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("drukarz", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("ekonomista", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("elektryk", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("energetyk", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("farmaceutka", "Przyrodniczy", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("farmaceutka lub przedszkolanka", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("foograf albo fryzjer", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("forogaf albo informatyk", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("fotograf", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("fotograf albo architekt", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("fotograf lub prawnik, ewentulanie co????? zwi??zanego", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("fryzjer", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("fryzjer lub dentysta", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("fryzjerka", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("fryzjerka albo przedszkolanka", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("fryzjerka, kosmetyczka", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("g????rnik", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("g??????wny specjalista ds..", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("g????wna ksi??gowa", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("gospodyni domowa", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("hadlowiec", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("handlowiec", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("hodowca zwierz??t", "Przyrodniczy", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("hydraulik", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("informatyk", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("informatyk i gracz komputerowy", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("informatyk programista", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("informatyk, fryzjer, kosmetyczka", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("informatyk, in??ynier", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("informatyk, programista, grafik komputerowy", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("informatyk, proplayer", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("informatyk, tw????rca gier", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("informatyk, zapa?????nik", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("in??ynier", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("in??ynier budowlany", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("je??dziec konny", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("jokerka albo nauczycielka plastyki", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("jubiler", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("kadrowa w ZUS", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("kelnerka", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("kierowca", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("kierowca ci??????ar????wki", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("kierowca TIR-????w", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("kierownik ds. kontroli ja", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("kierownik hurtowni", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("kierownik sklepu", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("kierownik wydzia??u", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("konserwator lewego brzgu", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("konsultantka Avon", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("kosmetyczka", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("kosmetyczka, makija????ystka", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("krawcowa", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("krawcowa, dekororka sal", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("krawiec", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("ksi??dz", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("ksi??goowa", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("kucharka", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("kucharz", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("kurator s??dowy", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("kwiaciarka", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("?????lusarz", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("?????piewak", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("labserwis", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("lakiernik", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("lekarz", "Przyrodniczy", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("lekarz i prawnik", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("lekarz lub hipoterapeuta", "Przyrodniczy", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("lekarz lub ksi??gowa", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("lekarz pediaatra", "Przyrodniczy", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("lekarz pediatra", "Przyrodniczy", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("lekarz, naukowiec, in??ynier", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("le??nik", "Przyrodniczy", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("????o??nierz", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("logopeda i nauczyciel", "Humanistyczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("????czy kable", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("magazynier", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("malarka i nauczycielka plastyki", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("maluje maszyny", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("masa????ysta za granic??", "Przyrodniczy", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("masarz", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("mechaink samochodowy", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("mechanik", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("mechanik i lakiernik", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("mechanik rowerowy, fryzjer, podr????????nik", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("mechanik samochodowy", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("mechanik sportowy", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("medycyna, policjatnka lub rolnik", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("menad????er klubu pi??karskiego", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("menad????er w banku", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("monta????ysta film????w", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("monter drzwi i okien", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("monter kamer i serwisant", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("murarz", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("nauczyciel", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("nauczyciel historii", "Humanistyczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("nauczyciel matematyki", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("nauczyciel wf-u", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("nauczyciel, lekarz", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("nauczycielka", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("nauczycielka biologii", "Przyrodniczy", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("nauczycielka geografii", "Przyrodniczy", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("nauczycielka j??z. Angiel", "Humanistyczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("nauczycielka polskiego", "Humanistyczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("nauczycielka przedsi??bio", "Humanistyczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("nauczycielka wf-u", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("nauczycielka wf-u lub lekarka", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("nauczycielka wf-u lub malarka", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("nauczycielka, piosenkarka, makijarzyystka", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("naukowiec", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("obs??uguje klient????w", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("ogrodniczka", "Przyrodniczy", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("ogrodnik", "Przyrodniczy", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("operator koparki", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("operator maszyn", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("operator w????zka wid??oweg", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("opiekunka", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("opiekunka dla dzieci, farmaceutka, nauczycielka lu", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("opiekunka dzieci", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("opiekunka w autobusie szk", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("organizator wycieczek", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("otworzy????? sswoj?? cukierni?? lub pracowa????? w domu", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("pakuje cz???????ci samochodo", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("pakuje kosmetyki", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("pedagog", "Humanistyczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("pedagog lub fotograf", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("pediatra lub neurolog", "Przyrodniczy", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("piekarz", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("piel??gniarka", "Przyrodniczy", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("pilot", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("pi??karz", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("pi??karz albo prezydent, premier", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("pi??karz lub informatyk", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("pi??karz lub murarz", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("pi??karz, ksi??dz, menad????er", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("piosenkara", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("pisarz komiks????w i filozof", "Humanistyczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("plantator", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("po?????rednik nieruchomo?????ci", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("policjant", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("policjant lub informatyk", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("policjant lub kryminolog", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("policjant lub stolarz", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("policjant lub Youtuber", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("policjantka", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("policjantka lub fryzjerka", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("po??o??na", "Przyrodniczy", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("praca przy komputerze", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("pracownik biurowy", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("pracownik kopalni", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("pracownik linii produkcyj", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("pracownik spo??eczny", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("pracownik ZUK", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("pracuje na stacji benzyno", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("pracuje w domu", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("pracuje w dworku", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("pracuje w fabryce ciastek", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("pracuje w firmie", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("pracuje w Interdruku", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("pracuje w kopalni", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("pracuje w kopalni piasku", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("pracuje w sedarze", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("pracuje w skupie z??omu", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("pracuje w szkole", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("prawnik", "Humanistyczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("prawnik lub lekarz", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("prawnik, lekarz, pi??karz", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("prezenterka telewizyjna lub s??dzia", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("produkuje sery", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("projektantka wn??trz", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("projektowanie motor????w albo stolarz", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("prowadzi firm?? budowlan??", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("prowadzi swoj?? firm?? br", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("prowadzi w??asn?? dzia??a", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("prowadzi????? stadnin?? koni", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("przedstawiciel handlowy", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("przedszkolanka", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("psycholog dzieci??cy", "Humanistyczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("ratownik, nauczyciel, weterynarz", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("recepcjonistka w hotelu", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("re????yserka lub aktorka", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("restaurator, szef kuchni", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("rolnik", "Przyrodniczy", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("rolnik (naprawa maszyn)", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("rolnik i kierowca TIR-????w", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("rolnik lub kierowca TIR-????w", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("sekretarka", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("s??dzia", "Humanistyczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("siatkarka", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("skrzypaczka", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("spawacz", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("specjalista ds. kadr i p??", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("sportowiec", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("sprawdza czy jest wszystk", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("sprawdza jako?????????? roli", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("sprz??taczka", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("sprzedawca", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("sprzedawca cz???????ci samoc", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("sprzedawca mebli", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("sprzedawca, rolnik", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("stewardesa", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("stolarz", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("stra????ak", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("szef ekipy budowlanej", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("szewc", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("szwaczka", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("taks????wkarz", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("tancerka", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("tancerka, nauczycielka wf, sprzedawca", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("tatua????ystka", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("technolog mebli", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("tester gier komputerowych", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("tokarz", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("tynkarz", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("urz??dnik", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("urz??dnik, sekretarz", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("w AVON", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("w banku", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("w biurze poselskim", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("w drukarni", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("w eletrociep??owni", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("w firmie obuwniczej", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("w firmie produkcyjnej", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("w firmie produkuj??cej ok", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("w firmie przewozowej", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("w gospodarstwie", "Przyrodniczy", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("w hotelu", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("w internecie", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("w kanalizacji", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("w MOP sortuje ?????mieci", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("w o?????rodku dla os????b niep", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("w o?????rodku opieku?????czym", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("w rolnictwie", "Przyrodniczy", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("w sklepie internetowym", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("w stra????y po????arnej", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("w szpitalu", "Przyrodniczy", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("w tartaku", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("w transporcie", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("w zak??adzie mi??snym", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("w zak??adzie produkcyjnym", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("w????jt gminy", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("wdra????a systemy integracy", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("weterynarz", "Przyrodniczy", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("weterynarz lub projektantka mody", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("weterynarz, pisarka albo podr????????niczka", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("w??dzi mi??so", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("wice dyrektor firmy", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("w??a??ciciel firmy motory", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("w??a??ciciel piekarni", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("w??a??ciciel restauracji", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("w??a??ciciel restauracji lub zak??adu fryzjerskieg", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("wojskowy", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("wstawia parapety", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("wyko?????czenia mieszka?????", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("wykonuje okna dachowe", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("wypisuje zam????wienia", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("youtuber (gamer)", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Youtuber, tester gier, DJ", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("zajmowa????? si?? motoryzacj??", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("zast??pca kierownika", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("zast??pca w????jta", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("zbiera ?????mieci", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("zrywa pieczarki", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Techniczny wn??trz", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne, Przyrodniczy", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne, dekororka sal", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne wf-u", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne w autobusie szk", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne przedsi??bio", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne polskiego", "Humanistyczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne mebli", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne j??z. Angiel", "Humanistyczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne geografii", "Przyrodniczy", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne biologii", "Przyrodniczy", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Przyrodzniczy", "Przyrodniczy", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne piasku", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Techniczny samochodowy", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne cz???????ci samoc", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Techniczny budowlany", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inneka", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Techniczny rowerowy, Inne, podr????????nik", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Przyrodznicze i Humanistyczny", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Techniczny, Inne, Inne", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Techniczny i Inne", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne, Inneka wf, Inne", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne albo Techniczny", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne lub Humanistyczny, ewentulanie co????? zwi??zanego", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne lub Techniczny", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("re????yserka lub Inne", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Humanistyczny lub Przyrodznicze", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Przyrodniczy lub projektantka mody", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Przyrodznicze pediatra", "Przyrodniczy", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Przyrodniczy lub Inne TIR-????w", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Przyrodniczy, pisarka albo podr????????niczka", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Humanistyczny lub Inne", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne matematyki", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Przyrodniczy i Inne TIR-????w", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inneka wf-u", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne, makija????ystka", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inneka, Inne", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne lub Inne", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne albo prezydent, premier", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Przyrodznicze", "Przyrodniczy", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne, sekretarz", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Przyrodznicze, Techniczny, Techniczny", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne lub Inne dzieci", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Przyrodznicze lub hipoterapeuta", "Przyrodniczy", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne, Przyrodznicze", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Humanistyczny, Przyrodznicze, Inne", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne, Inne, menad????er", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne lub redaktorka gazety", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("youtuber (gamer)", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Techniczny, Techniczny, modelka, Inne", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne ci??????ar????wki", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Przyrodznicze pediaatra", "Przyrodniczy", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Przyrodniczy (naprawa maszyn)", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne lub Inneka", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inneka albo Inne", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inneka, piosenkarka, makijarzyystka", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inneka wf-u lub lekarka", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne albo Inne dzieci2", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inneka wf-u lub malarka", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne lub dentysta", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne dla dzieci, Przyrodniczy, Inneka lu", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Przyrodznicze lub ksi??gowa", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne lub zak??adu Inneskieg", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne dzieci", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Techniczny sportowy", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Przyrodniczy lub Inne", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne lub Youtuber", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Techniczny, tw????rca gier", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne, Inne wf, Inne", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne lub kryminolog", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Humanistyczny lub Przyrodniczy", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Techniczny programista", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Techniczny, programista, grafik komputerowy", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne, Inne", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Techniczny, zapa?????nik", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Techniczny, proplayer", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Techniczny, Techniczny", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Techniczny i gracz komputerowy", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Przyrodniczy, Techniczny, Techniczny", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Humanistyczny, Przyrodniczy, Inne", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("youtuber (gamer)", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Przyrodniczy (naprawa maszyn)", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inneka", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne albo Inne", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne, piosenkarka, makijarzyystka", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne lub lekarka", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne albo Inne2", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne lub malarka", "Inne", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne dla dzieci, Przyrodniczy, Inne lu", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Przyrodniczy, Techniczny", NA, ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Inne2", "Inne", ankieta$zaw??d_u)


ankieta$zaw??d_u<-sub("youtuber (gamer)", "Techniczny", ankieta$zaw??d_u)
ankieta$zaw??d_u<-sub("Przyrodniczy (naprawa maszyn)", NA, ankieta$zaw??d_u)
ankieta[ankieta$id_ucznia=="3502","zaw??d_u"] = NA
ankieta[ankieta$id_ucznia=="1910","zaw??d_u"] = "Techniczny"

df=c(ankieta$zaw??d_matki,ankieta$zaw??d_ojciec,ankieta$zaw??d_u)
df=unique(df)
View(as.array(df))
write.csv(ankieta, file = "ankieta_clr.csv")
